
import { Quest, Rank, Rival } from './types';
import BrushIcon from './components/icons/BrushIcon';
import GemIcon from './components/icons/GemIcon';
import TrophyIcon from './components/icons/TrophyIcon';
import RivalIcon from './components/icons/RivalIcon';

export const ARTIST_RANKS: Rank[] = [
  { title: "Ink Initiate", xpRequired: 0, nextLevelXp: 100, icon: BrushIcon },
  { title: "Chroma Cadet", xpRequired: 100, nextLevelXp: 300, icon: GemIcon },
  { title: "Form Forger", xpRequired: 300, nextLevelXp: 700, icon: TrophyIcon },
  { title: "Perspective Prodigy", xpRequired: 700, nextLevelXp: 1500, icon: RivalIcon },
  { title: "Anatomy Archon", xpRequired: 1500, nextLevelXp: 3000, icon: BrushIcon },
  { title: "Render Renegade", xpRequired: 3000, nextLevelXp: 5000, icon: GemIcon },
  { title: "Composition King", xpRequired: 5000, nextLevelXp: 10000, icon: TrophyIcon },
  { title: "Storytelling Sovereign", xpRequired: 10000, nextLevelXp: 99999, icon: RivalIcon },
];

export const SEVEN_DAY_CHALLENGE: Quest[] = [
  {
    day: 1,
    title: "Gesture Drawing: 30-Second Poses",
    description: "Capture the essence of movement. Draw five figures from reference photos, spending only 30 seconds on each. Don't focus on detail, only on the flow and energy of the pose.",
    category: 'Gesture',
    rewards: { xp: 50, aetherShards: 20 },
  },
  {
    day: 2,
    title: "Value Study: Sphere & Cube",
    description: "Understand light and shadow. Draw a simple sphere and a cube, then shade them as if lit by a single, strong light source from the top-left. Focus on creating a full range of values from light to dark.",
    category: 'Composition',
    rewards: { xp: 60, aetherShards: 25 },
  },
  {
    day: 3,
    title: "Color Theory: Complementary Colors",
    description: "Create a simple composition (e.g., a piece of fruit on a table) and color it using only a pair of complementary colors (like red and green, or blue and orange) plus black and white.",
    category: 'Color Theory',
    rewards: { xp: 75, aetherShards: 30 },
  },
  {
    day: 4,
    title: "Anatomy: The Human Hand",
    description: "Draw your own non-dominant hand in a relaxed pose. Pay close attention to the proportions of the palm, fingers, and thumb. Simplify the complex forms into basic shapes first.",
    category: 'Anatomy',
    rewards: { xp: 100, aetherShards: 40 },
  },
  {
    day: 5,
    title: "Storytelling: A Single Object",
    description: "Choose a mundane object from your room (a cup, a shoe, a key) and draw it in a way that tells a story. Is it old and worn? Brand new? Used for something unexpected? Use lighting and composition to hint at its history.",
    category: 'Storytelling',
    rewards: { xp: 120, aetherShards: 50 },
  },
  {
    day: 6,
    title: "Composition: Rule of Thirds",
    description: "Create a simple landscape or cityscape. Place the most important element of your drawing not in the center, but at one of the intersections of a 3x3 grid overlaid on your canvas.",
    category: 'Composition',
    rewards: { xp: 140, aetherShards: 60 },
  },
  {
    day: 7,
    title: "Challenge Fusion: The Quest-Giver",
    description: "Combine everything you've learned. Draw a character who could give you a quest. Use gesture for a dynamic pose, anatomy for believable form, color and value for mood, and composition to frame them as an important figure.",
    category: 'Anatomy',
    rewards: { xp: 200, aetherShards: 100 },
  },
];

export const RIVAL_DATA: Rival = {
    name: "Silas Vex",
    rank: "Render Renegade",
    mastery: "Character Design",
    avatarUrl: "https://picsum.photos/seed/rival/100/100"
};

export const UI_TEXT = {
    marketing: {
        headline: "Stop Guessing. Start Growing. Forge Your Artistic Legacy.",
        subheadline: "ArtForge is your personal AI art mentor. Conquer daily quests, receive instant, expert critique, and rise through the ranks to become a master.",
        cta: "Begin Your Forging"
    },
    monetization: {
        title: "ArtForge Pro",
        description: "Unlock your full potential with a Pro subscription. Gain access to advanced questlines, personalized learning paths generated by AI, in-depth critique history, and exclusive cosmetic rewards to customize your profile.",
        ideas: [
            "Monthly/Yearly Subscription for Pro features.",
            "Aether Shard packs for purchasing cosmetic items or unlocking special one-off boss battles.",
            "Pay-per-critique for professional artist feedback (a future goal)."
        ]
    }
};
